name: check-outputs
on: push
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: r-lib/actions/setup-r@v2
              with:
                r-version: '4.5.1' # The R version to download (if necessary) and use.
                # Use "renv" to retrieve R version recorded in renv.lock file.
            - run: Rscript a_order_of_commands.R
